# conteúdo mínimo do script.py.mako

"""up db

Revision ID: cbb9222c4e0b
Revises: ab108b4c5fc2
Create Date: 2025-12-15 09:49:26

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cbb9222c4e0b'
down_revision = 'ab108b4c5fc2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
